### ISSUE TITLE
dude is inherently sexist

### ISSUE THREAD

**Issue by izzy** [strand/dude#29]
The word "dude" refers to a male person and as such should not be used to address a developer or user who might see this.

The word uses should be gender-neutral, bias-free term of address that lets cis, trans and non-binary people equally assume this is for them.

**Comment by plicjo** [comment]
Really, dude?

**Comment by johana-star** [comment]
Hey @izzy. I appreciate your concerns, and also, disagree with your assessment.

Firstly, I am non-binary and trans, so I believe I have the lived experience to differentiate gendered language which is exclusionary from that that is humorous.

Secondly, this project was meant as a joke. It is not a joke merely in the sense that it inserts a somewhat funny response into exceptions when raised, but also as a reference to the Coen Brothers' movie _The Big Lebowski (1998)_. The overriding of exceptions is meant to highlight when a coder is "out of their element," like the protagonist of _The Big Lebowski (1998)_.

This gem is not currently under active maintenance, and so, I am closing this issue, but I also want to commend you for raising concerns, and specifically request that if you still feel strongly about this issue, that you go ahead and fork this project. I would welcome and integrate any technical improvements you make on your fork, however, I will not alter the language emitted by `dude`.

Regards,
💗 Johana 💗
